export const TAGLIST: Object = {
    ["English"]: "assets/mat-icons/text_format_white_48dp.svg",
    ["Hindi"]: "assets/mat-icons/description_white_48dp.svg",
    ["Sanskrit"]: "assets/mat-icons/translate_white_48dp.svg",
    ["Maths"]: "assets/mat-icons/functions_white_48dp.svg",
    ["Social Science"]: "assets/mat-icons/groups_white_48dp.svg",
    ["History"]: "assets/mat-icons/history_edu_white_48dp.svg",
    ["Geography"]: "assets/mat-icons/terrain_white_48dp.svg",
    ["Civics"]: "assets/mat-icons/balance_white_48dp.svg",
    ["Science"]: "assets/mat-icons/science_white_48dp.svg",
    ["Physics"]: "assets/mat-icons/lightbulb_white_48dp.svg",
    ["Chemistry"]: "assets/mat-icons/co2_white_48dp.svg",
    ["Biology"]: "assets/mat-icons/biotech_white_48dp.svg",
    ["Computer"]: "assets/mat-icons/mouse_white_48dp.svg",
    ["F.I.T."]: "assets/mat-icons/mouse_white_48dp.svg",
    ["I.P."]: "assets/mat-icons/mouse_white_48dp.svg",
    ["General Knowledge"]: "assets/mat-icons/newspaper_white_48dp.svg",
    ["Art & Craft"]: "assets/mat-icons/palette_white_48dp.svg",
    ["Economics"]: "assets/mat-icons/monetization_on_white_48dp.svg",
    ["Business Studies"]: "assets/mat-icons/business_white_48dp.svg",
    ["Accounts"]: "assets/mat-icons/account_balance_white_48dp.svg",
    ["Music"]: "assets/mat-icons/piano_white_48dp.svg",
    ["Dance"]: "assets/mat-icons/theater_comedy_white_48dp.svg",
    ["Legal Studies"]: "assets/mat-icons/policy_white_48dp.svg",
    ["Physical Education"]: "assets/mat-icons/sports_handball_white_48dp.svg",
    ["Psychology"]: "assets/mat-icons/psychology_white_48dp.svg"
}